services:
  accounts:
    image: "puzzledsunrise/accounts:1.0.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankingApp
  loans:
    image: "puzzledsunrise/loans:1.0.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankingApp
  cards:
    image: "puzzledsunrise/cards:1.0.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankingApp
networks:
  bankingApp:
    driver: "bridge"