build:
  version: "1.0.0"

accounts:
  message: "Welcome to cards service related prod APIs "
  contactDetails:
    name: "Shawn Sun - Product Owner"
    email: "apple.splandy@gmail.com"
  onCallSupport:
    - 12345
    - 23456