# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: puzzledsunrise/gatewayserver
  tag: 9.0.0

containerPort: 8072

service:
  #exposes the service outside the cluster using a cloud provider’s load balancer
  type: LoadBalancer
  port: 8072
  targetPort: 8072

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
#validate access tokens and enforce role-based access via Keycloak, Auth0
resouceserver_enabled: true
otel_enabled: true
#gateway does not need to produce or consume messages from Kafka
kafka_enabled: false