services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - bankingApp

  configserver:
    image: "puzzledsunrise/configserver:4.0.0"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - bankingApp
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  eurekaserver:
    image: "puzzledsunrise/eurekaserver:4.0.0"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankingApp
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

  accounts:
    image: "puzzledsunrise/accounts:4.0.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankingApp
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/


  loans:
    image: "puzzledsunrise/loans:4.0.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankingApp
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: "puzzledsunrise/cards:4.0.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankingApp
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  gatewayserver:
    image: "puzzledsunrise/gatewayserver:4.0.0"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankingApp
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  bankingApp:
    driver: "bridge"
#
#services:
#  rabbit:
#    image: rabbitmq:3.13-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    networks:
#      - bankingApp
#
#  configserver:
#    image: "puzzledsunrise/configserver:3.0.0"
#    container_name: configserver-ms
#    ports:
#      - "8071:8071"
#    depends_on:
#      rabbit:
#        condition: service_healthy
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    networks:
#      - bankingApp
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbit"
#
#  accounts:
#    image: "puzzledsunrise/accounts:1.0.0"
#    container_name: accounts-ms
#    ports:
#      - "8080:8080"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - bankingApp
#    environment:
#      SPRING_APPLICATION_NAME: "accounts"
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#
#
#  loans:
#    image: "puzzledsunrise/loans:1.0.0"
#    container_name: loans-ms
#    ports:
#      - "8090:8090"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - bankingApp
#    environment:
#      SPRING_APPLICATION_NAME: "loans"
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#
#  cards:
#    image: "puzzledsunrise/cards:2.0.0"
#    container_name: cards-ms
#    ports:
#      - "9000:9000"
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - bankingApp
#    environment:
#      SPRING_APPLICATION_NAME: "cards"
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#
#  eurekaserver:
#    image: "puzzledsunrise/eurekaserver:3.0.0"
#    container_name: eurekaserver-ms
#    ports:
#      - "8070:8070"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    networks:
#      - bankingApp
#
#networks:
#  bankingApp:
#    driver: "bridge"